#!/bin/bash

set -e

REPO_URL="https://github.com/tbnobed/mover.git"
INSTALL_DIR="/opt/color-routing-orchestrator"
SERVICE_NAME="color-routing-orchestrator"
DB_NAME="color_routing"
DB_USER="color_routing"

echo "=============================================="
echo "  Color Routing System - Orchestrator Installer"
echo "=============================================="
echo ""

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (use sudo)"
  exit 1
fi

echo "This script will install/reinstall the Color Routing Orchestrator."
echo ""

read -p "Enter domain or IP for this server [localhost]: " SERVER_HOST < /dev/tty
SERVER_HOST=${SERVER_HOST:-localhost}

read -p "Enter a database password [colorpass123]: " DB_PASSWORD < /dev/tty
DB_PASSWORD=${DB_PASSWORD:-colorpass123}

read -p "Enter a session secret [autogenerated]: " SESSION_SECRET < /dev/tty
SESSION_SECRET=${SESSION_SECRET:-$(openssl rand -hex 32)}

read -p "Enter storage path for incoming files [/data/incoming]: " STORAGE_PATH < /dev/tty
STORAGE_PATH=${STORAGE_PATH:-/data/incoming}

read -p "Enter daemon API key for site daemons [autogenerated]: " DAEMON_API_KEY < /dev/tty
DAEMON_API_KEY=${DAEMON_API_KEY:-$(openssl rand -hex 32)}

echo ""
echo "Configuration:"
echo "  Server Host: ${SERVER_HOST}"
echo "  Database Password: ****"
echo "  Daemon API Key: ****"
echo "  Storage Path: ${STORAGE_PATH}"
echo ""

echo "Step 1: Stopping existing services..."
systemctl stop ${SERVICE_NAME} 2>/dev/null || true
systemctl disable ${SERVICE_NAME} 2>/dev/null || true

echo ""
echo "Step 2: Installing system dependencies..."
apt-get update -qq
apt-get install -y curl git postgresql postgresql-contrib python3 python3-pip python3-venv nginx openssl

if ! command -v node &> /dev/null || [[ $(node -v | cut -d'.' -f1 | tr -d 'v') -lt 18 ]]; then
  echo "Installing Node.js 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi

echo ""
echo "Step 3: Setting up PostgreSQL..."
systemctl start postgresql
systemctl enable postgresql

echo "Resetting database and user..."
sudo -u postgres psql -c "DROP DATABASE IF EXISTS ${DB_NAME};" 2>/dev/null || true
sudo -u postgres psql -c "DROP USER IF EXISTS ${DB_USER};" 2>/dev/null || true
sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';" 2>/dev/null || \
  sudo -u postgres psql -c "ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';"
sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};" 2>/dev/null || true
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
sudo -u postgres psql -c "ALTER DATABASE ${DB_NAME} OWNER TO ${DB_USER};" 2>/dev/null || true
echo "Database setup complete."

echo ""
echo "Step 4: Cloning/updating repository..."
if [ -d "$INSTALL_DIR" ]; then
  echo "Updating existing installation..."
  cd "$INSTALL_DIR"
  git fetch origin
  git reset --hard origin/main
else
  git clone "$REPO_URL" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

echo ""
echo "Step 5: Installing Node.js dependencies..."
npm install

echo ""
echo "Step 6: Setting up Python virtual environment..."
rm -rf ${INSTALL_DIR}/venv
python3 -m venv ${INSTALL_DIR}/venv
${INSTALL_DIR}/venv/bin/pip install --upgrade pip
${INSTALL_DIR}/venv/bin/pip install fastapi uvicorn asyncpg pydantic aiofiles python-multipart bcrypt

echo ""
echo "Step 7: Creating environment file..."
mkdir -p ${STORAGE_PATH}
cat > ${INSTALL_DIR}/.env << EOF
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}
SESSION_SECRET=${SESSION_SECRET}
DAEMON_API_KEY=${DAEMON_API_KEY}
STORAGE_PATH=${STORAGE_PATH}
PYTHON_BIN=${INSTALL_DIR}/venv/bin/python3
NODE_ENV=production
PORT=5000
EOF
echo "Environment file created."

echo ""
echo "Step 8: Building frontend..."
cd ${INSTALL_DIR}
npm run build

echo ""
echo "Step 9: Running database migrations..."
npm run db:push

echo ""
echo "Step 9b: Granting permissions on all tables..."
sudo -u postgres psql -d ${DB_NAME} -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_USER};"
sudo -u postgres psql -d ${DB_NAME} -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER};"
sudo -u postgres psql -d ${DB_NAME} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_USER};"
sudo -u postgres psql -d ${DB_NAME} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DB_USER};"
echo "Permissions granted."

echo ""
echo "Step 10: Creating systemd service..."
cat > /etc/systemd/system/${SERVICE_NAME}.service << EOF
[Unit]
Description=Color Routing System Orchestrator
After=network.target postgresql.service

[Service]
Type=simple
User=root
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=/usr/bin/npx tsx server/production.ts
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

echo ""
echo "Step 11: Configuring Nginx reverse proxy..."
cat > /etc/nginx/sites-available/${SERVICE_NAME} << EOF
server {
    listen 80;
    server_name ${SERVER_HOST};

    client_max_body_size 10G;

    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }
}
EOF

ln -sf /etc/nginx/sites-available/${SERVICE_NAME} /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx

echo ""
echo "Step 12: Starting services..."
systemctl daemon-reload
systemctl enable ${SERVICE_NAME}
systemctl start ${SERVICE_NAME}

echo ""
echo "Waiting for service to start..."
sleep 5

echo ""
echo "Step 13: Verifying installation..."
if systemctl is-active --quiet ${SERVICE_NAME}; then
  echo "Service is running!"
else
  echo "Warning: Service may not be running. Check with: journalctl -u ${SERVICE_NAME} -f"
fi

echo ""
echo "=============================================="
echo "  Installation Complete!"
echo "=============================================="
echo ""
echo "Orchestrator URL: http://${SERVER_HOST}"
echo "Storage Path: ${STORAGE_PATH}"
echo ""
echo "Daemon API Key (SAVE THIS for site daemon setup):"
echo "  ${DAEMON_API_KEY}"
echo ""
echo "First-time Setup:"
echo "  1. Open http://${SERVER_HOST} in your browser"
echo "  2. Complete the setup wizard to create your admin account"
echo "  3. Add sites through the Sites page"
echo ""
echo "Service commands:"
echo "  sudo systemctl status ${SERVICE_NAME}"
echo "  sudo systemctl restart ${SERVICE_NAME}"
echo "  sudo journalctl -u ${SERVICE_NAME} -f"
echo ""
echo "Next steps:"
echo "  1. Complete the setup wizard in your browser"
echo "  2. Set up SSL with: sudo certbot --nginx -d ${SERVER_HOST}"
echo "  3. Install daemons at each site with the API key shown above"
echo ""
